package platform

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const unitName = "t3-steward.service"

const generatedMarker = "# Generated by t3-steward install-service. Re-run with --force to regenerate."

type systemdUser struct{}

func (s *systemdUser) unitPath() (string, error) {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(configDir, "systemd", "user", unitName), nil
}

// RenderUnit produces the unit file text.
func RenderUnit(opts InstallOptions) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n")
	b.WriteString("[Unit]\n")
	b.WriteString("Description=T3 quota watchdog (stops T3 agent sessions before the provider quota runs out)\n")
	b.WriteString("Documentation=https://github.com/iryzhkov/t3-steward\n")
	if opts.T3Unit != "" {
		fmt.Fprintf(&b, "After=%s\n", opts.T3Unit)
		// PartOf stops the watchdog together with T3 without pulling T3
		// in when the watchdog starts on its own.
		fmt.Fprintf(&b, "PartOf=%s\n", opts.T3Unit)
	}
	b.WriteString("\n[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=%s run --config %s\n", shellQuote(opts.Binary), shellQuote(opts.ConfigPath))
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=5\n")
	b.WriteString("# The default token command runs the t3 CLI, which needs node on PATH.\n")
	fmt.Fprintf(&b, "Environment=PATH=%s\n", servicePath())
	b.WriteString("Environment=HOME=%h\n")
	b.WriteString("# Modest hardening. ProtectHome is deliberately absent: the watchdog\n")
	b.WriteString("# reads T3's logs and the t3 CLI writes T3's own database under $HOME.\n")
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("PrivateTmp=true\n")
	b.WriteString("ProtectSystem=full\n")
	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")
	return b.String()
}

// servicePath builds the PATH baked into the unit: the installer's PATH so
// that the same node and t3 resolve as in the user's shell.
func servicePath() string {
	p := os.Getenv("PATH")
	if p == "" {
		p = "/usr/local/bin:/usr/bin:/bin"
	}
	home, err := os.UserHomeDir()
	if err == nil && home != "" {
		p = strings.ReplaceAll(p, home, "%h")
	}
	return p
}

func shellQuote(s string) string {
	if !strings.ContainsAny(s, " \t\"'\\$") {
		return s
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, `$`, `\$`).Replace(s) + `"`
}

func (s *systemdUser) Install(opts InstallOptions) (*InstallResult, error) {
	path, err := s.unitPath()
	if err != nil {
		return nil, err
	}
	if opts.T3Unit == "" {
		if _, err := os.Stat(filepath.Join(filepath.Dir(path), "t3code.service")); err == nil {
			opts.T3Unit = "t3code.service"
		}
	}
	content := RenderUnit(opts)
	if existing, err := os.ReadFile(path); err == nil {
		if !bytes.Equal(existing, []byte(content)) && !opts.Force {
			if !bytes.HasPrefix(existing, []byte(generatedMarker)) {
				return nil, fmt.Errorf("%s exists and was not generated by this tool; pass --force to overwrite it", path)
			}
			return nil, fmt.Errorf("%s exists with different content; pass --force to overwrite it", path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return nil, err
	}
	res := &InstallResult{Path: path}
	res.Commands = []string{
		"systemctl --user daemon-reload",
		"systemctl --user enable --now " + unitName,
		"systemctl --user status " + unitName,
		"journalctl --user -u " + unitName + " -f",
	}
	if _, err := exec.LookPath("systemctl"); err == nil {
		if out, err := exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput(); err != nil {
			res.Notes = append(res.Notes, "systemctl --user daemon-reload failed: "+strings.TrimSpace(string(out)))
		}
		if opts.Enable {
			if out, err := exec.Command("systemctl", "--user", "enable", "--now", unitName).CombinedOutput(); err != nil {
				return res, fmt.Errorf("enable service: %s", strings.TrimSpace(string(out)))
			}
			res.Notes = append(res.Notes, "service enabled and started")
		}
	}
	if opts.DryRun {
		res.Notes = append(res.Notes,
			"The service runs in dry-run mode until policy.dry_run is set to false in "+opts.ConfigPath+".")
	} else {
		res.Notes = append(res.Notes,
			"policy.dry_run is false in "+opts.ConfigPath+": the service will send messages and interrupt threads.")
	}
	res.Notes = append(res.Notes,
		"Enable lingering so the service also runs while you are logged out: loginctl enable-linger $USER")
	return res, nil
}

func (s *systemdUser) Uninstall() (*InstallResult, error) {
	path, err := s.unitPath()
	if err != nil {
		return nil, err
	}
	res := &InstallResult{Path: path}
	if _, err := exec.LookPath("systemctl"); err == nil {
		_ = exec.Command("systemctl", "--user", "disable", "--now", unitName).Run()
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	if _, err := exec.LookPath("systemctl"); err == nil {
		_ = exec.Command("systemctl", "--user", "daemon-reload").Run()
	}
	res.Notes = append(res.Notes, "Configuration and state were left in place.")
	return res, nil
}

func (s *systemdUser) StatusHint() []string {
	return []string{
		"systemctl --user status " + unitName,
		"journalctl --user -u " + unitName + " -n 100",
	}
}
